version: "3"

services:
  
  db:
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - mollys_pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
  
  mollys:
    restart: always
#    build: .
    image: mollys:latest
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    volumes:
      - .:/srv/mollys
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mollys_pgdata:
    external: true
