version: "3"

services:
  
  db:
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - mollys_pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
  
  mollys:
    restart: always
    build:
      context: .
      dockerfile: container-build/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    volumes:
      - mollys_app:/srv/mollys
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl --fail http://0.0.0.0:8000/mollys/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mollys_pgdata:
    external: true
  mollys_app:
    external: true
