# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-09 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_add_emails_to_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email alternativo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
    ]
