# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-09 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_emails_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='person',
            name='floor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='floor'),
        ),
    ]
