# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_floor_on_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='floor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='floor'),
        ),
    ]
