# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_field_floor_on_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\xe1rea'),
        ),
        migrations.AlterField(
            model_name='person',
            name='floor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='piso'),
        ),
    ]
