# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 13:29
from __future__ import unicode_literals

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_fields_area_and_floor_on_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['name'], 'verbose_name': 'Secretar\xeda', 'verbose_name_plural': 'offices'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='invalid_value', regex=b'^\\d{6,10}$')], verbose_name='N\xfamero Documento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DocumentType', verbose_name='document_type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='group_id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ldap_user_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[app.models.validate_ldap_user_name], verbose_name='ldap_user_name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='received_application',
            field=models.BooleanField(default=False, verbose_name='received_application'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
