# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 11:01
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_update_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[app.models.validate_email_domain], verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ldap_user_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[app.models.validate_ldap_user_name], verbose_name='Usuario ldap'),
        ),
    ]
